# Generated by Django 6.1.1 on 2026-10-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
